### ISSUE TITLE
shodan.exception.APIError: Invalid API key

### ISSUE THREAD

**Issue by mohammed-sec2010** [pielco11/fav-up#1]
root@dsfsf7:/home/mohammed_sec2010/fav-up# python3 favUp.py --favicon-url https://www.zxzxzxzx.com/assets/favicon.ico
Mask-IP: xx.xxx.x.x.x
Mask-ISP: CLOUDFLARENET
Favicon Hash: 1ccccccccccc
Traceback (most recent call last):
  File "favUp.py", line 51, in <module>
Traceback (most recent call last):
  File "favUp.py", line 51, in <module>
    shodanSearch(favhash)
  File "favUp.py", line 28, in shodanSearch
    results = shodan.search(f"http.favicon.hash:{favhash}")
  File "/usr/local/lib/python3.7/site-packages/shodan/client.py", line 498, in search
    return self._request('/shodan/host/search', args)
  File "/usr/local/lib/python3.7/site-packages/shodan/client.py", line 321, in _request
    raise APIError(error)
shodan.exception.APIError: Invalid API key

**Comment by pielco11** [comment]
Are you sure that your API is valid? Does `SHODAN_API.txt` contain the key?

**Comment by mremployee** [comment]
Just replace this line, 

`shodan = Shodan(open("SHODAN_API.txt", "r").readline())`

with 

```
shodan = Shodan(open("SHODAN_API.txt", "r").readline().strip())
```

**Comment by mremployee** [comment]
If you're already using the Shodan CLI then you can simplify the process using the Python below:

```
from shodan.cli.helpers import get_api_key
api = Shodan(get_api_key())
```

[Source](https://twitter.com/shodanhq/status/1177696509216854018)
