### ISSUE TITLE
Bypass cloudflare captcha

### ISSUE THREAD

**Issue by aancw** [pielco11/fav-up#13]
Sometimes the target is blocked by cloudflare captcha when doing scraping.

**Comment by pielco11** [comment]
That would be tricky, really tricky. I'd suggest to save in file which domains have asked to solve a captcha challenge so that the user will check them out manually, save the favicon locally and then run the script.

**Comment by aancw** [comment]
Nice idea. Need to parse the html and give user warning like something "Captcha Detected".

**Comment by pielco11** [comment]
Do you have any website to test? The `status code` should be different, if I recall correctly

**Comment by aancw** [comment]
I will save the result later when facing the same issue again.

**Comment by pielco11** [comment]
Just tested it, returned status is 403 (quite expected)

**Comment by pielco11** [comment]
It turns out that some juicy information is added to the cookies

![immagine](https://user-images.githubusercontent.com/17363750/66771544-14a94780-eeaa-11e9-9207-e9d760602551.png)

Left clean session, first seen, captcha challenge asked. Right, captcha challenge solved

**Comment by pielco11** [comment]
So I guess that we can just check the response code, and in that case check for `CF-Chl-Bypass` is the response headers

**Comment by aancw** [comment]
When it happens? And what's the trigger?

**Comment by pielco11** [comment]
I tested with a clean browser and IP, no cookies, no cache, nothing. In such situation resolving a captcha challenge is required, once solved the cookie will last a while (no need to solve a new captcha challenge)

**Comment by aancw** [comment]
We need to implement custom cookie from user?

**Comment by pielco11** [comment]
I'd would implement handling response headers to check if the website is asking us to solve a captcha challenge. Then the user, once validated the captcha challenge, will save the favicon via "DevTools" bar (it's possible) and so run a lookup for that saved favicon

IMHO, handling cookies is not need

**Comment by aancw** [comment]
Okay. So we just give a warning to the user that CF asking a captcha and let user supplied favicon-url instead.

**Comment by pielco11** [comment]
The user will have to save locally the favicon icon, otherwise, if he/she will lookup by favicon-url, he/she will still get asked to resolve the captcha challenge

**Comment by aancw** [comment]
Yep. The point is we will give the user a warning when it happens.

**Comment by pielco11** [comment]
Agreed
