### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dbenji** [pielco11/fav-up#14]
Hi Francesco,
fav-up returns this error on line 131

File "favUp.py", line 131
    self._iterator.set_description(f'[+] Using Favicon Hash as parameter')
                                                                        ^
SyntaxError: invalid syntax

command run: python3 favUp.py –favicon-url http://www.EXAMPLE.com/favicon.ico

**Comment by pielco11** [comment]
Which python version are running? Please try with Python 3.6.x at least

**Comment by dbenji** [comment]
I was using version Python 3.5.3 like an idiot...:(
Tried with Python 3.8.1 and had some issue
Traceback (most recent call last):
  File "favUp.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Then tried with Python 3.6.4 and worked like a charm...unfortunately, even the favicon was there, no found_ips was identified.

Thanks for the support

**Comment by pielco11** [comment]
`ModuleNotFoundError: No module named 'requests'` you have to install requests for python 3.8.1
