### ISSUE TITLE
it doesn't work on routers for some reason.

### ISSUE THREAD

**Issue by minanagehsalalma** [pielco11/fav-up#15]
shodan generates a different  hash than the tool does and also the modems doesn't use the fav.icon direct url but 

a custom one like images/banner.ico

or even gifs 

so what's the work around ?

**Comment by pielco11** [comment]
1) do you have a concrete and documented example?

2) Use the `-fu` / `--favicon-url` argument

**Comment by minanagehsalalma** [comment]
@pielco11 
```
python favUp.py --favicon-url https://xx.xxx.xxx.xxx/favicon.ico -sc
[+] iterating over favicon URLs | processing https://xx.xxx.xxx.xxx/favicon.ico: : 0it [00:00, ?it/s]
```

just tried it works thanks 😁
