### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by qodirovhamidjon** [pielco11/fav-up#3]
python3 favUp.py --web https://example.com
Traceback (most recent call last):
  File "favUp.py", line 44, in <module>
    deepConnectionLens(data)
  File "favUp.py", line 33, in deepConnectionLens
    mIP = list(response.raw._connection.sock.getpeername())[0]
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'

**Comment by pielco11** [comment]
Please run `pip3 install --upgrade requests`

**Comment by qodirovhamidjon** [comment]
All the same, the same error

**Comment by pielco11** [comment]
@qodirovhamidjon may you show us the output of `pip3 show requests`, please?

**Comment by qodirovhamidjon** [comment]
pip3 show requests
Name: requests
Version: 2.22.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /home/ubuntu/.local/lib/python3.6/site-packages
Requires: certifi, urllib3, idna, chardet

**Comment by pielco11** [comment]
@qodirovhamidjon `python3 --version` ?

**Comment by qodirovhamidjon** [comment]
Python 3.6.8

**Comment by pielco11** [comment]
@qodirovhamidjon are using a VPN/proxy/something? Are you able to reach the target with your browser, for example?

**Comment by qodirovhamidjon** [comment]
I use your tools on Amazon EC2, I don’t use vpn at all

**Comment by qodirovhamidjon** [comment]
through the browser I see target

**Comment by pielco11** [comment]
@qodirovhamidjon might be possible to know the target so that I can dig without keeping asking you "try this", "look at that" and so on?

**Comment by qodirovhamidjon** [comment]
tell you the target

**Comment by qodirovhamidjon** [comment]
https://bitso.com

**Comment by pielco11** [comment]
I don't get errors, plus Shodan does not return any result for that favicon hash

![immagine](https://user-images.githubusercontent.com/17363750/65815305-5e710d00-e1dd-11e9-947d-18b5385bd71a.png)

![immagine](https://user-images.githubusercontent.com/17363750/65815307-6630b180-e1dd-11e9-8885-7b1690d15e07.png)

**Comment by qodirovhamidjon** [comment]
🤔🤔🤔🤔

**Comment by pielco11** [comment]
Really strange.

As of now the only workaround that I can suggest you is to comment lines 33, 34 and 35. and add a `return` statement. You'll not be able to see the Cloudflare IP but still be able to use this tool.

You could find the Cloudflare IP pinging the target: `ping target.com`
And for the whois you can use `https://viewdns.info/` for example

**Comment by aancw** [comment]
I think I fix the issue. Can you clarify with in my branch?

https://github.com/pielco11/fav-up/tree/petruknisme-patch

@qodirovhamidjon @pielco11

**Comment by strasharo** [comment]
Same here:

```
[user@localhost fav-up]$ pip3 show requests
Name: requests
Version: 2.22.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /home/user/.local/lib/python3.7/site-packages
Requires: urllib3, certifi, idna, chardet
Required-by: shodan, requests-ftp, requests-file
[user@localhost fav-up]$ python3 --version
Python 3.7.4
[user@localhost fav-up]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 30 (Thirty)
Release:	30
Codename:	Thirty
[user@localhost fav-up]$ python3 favUp.py --web https://<obscured>/
Traceback (most recent call last):
  File "favUp.py", line 44, in <module>
    deepConnectionLens(data)
  File "favUp.py", line 33, in deepConnectionLens
    mIP = list(response.raw._connection.sock.getpeername())[0]
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'
[user@localhost fav-up]$ 


```

**Comment by aancw** [comment]
Hi, All

Can you do `git pull` and then re-run the script? Please let me know

**Comment by strasharo** [comment]
Yup, works fine now, thanks @aancw .

**Comment by aancw** [comment]
Glad to hear that. @qodirovhamidjon please do `git pull`. Closed this issue.
